name: terraform destroy

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  ARM_CLIENT_ID: ${{ vars.AZURE_CLIENT_ID }}
  ARM_TENANT_ID: ${{ vars.AZURE_TENANT_ID }}
  ARM_SUBSCRIPTION_ID: ${{ vars.AZURE_SUBSCRIPTION_ID }}
  ARM_USE_OIDC: "true"
  TF_VAR_authorized_ip_ranges: ${{ vars.TF_VAR_AUTHORIZED_IP_RANGES }}

jobs:
  destroy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform/env/dev
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
      - run: terraform init
      - run: terraform destroy -auto-approve
